apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sampleApp.name }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    external-dns.alpha.kubernetes.io/hostname: {{.Values.sampleApp.service.host}}
  namespace: {{ .Values.sampleApp.namespace }}
  labels:
    app: {{ .Values.sampleApp.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.sampleApp.service.externalPort }}
      targetPort: {{ .Values.sampleApp.service.internalPort }}
      protocol: TCP
      name: {{ .Values.sampleApp.name }}
  selector:
    app: {{ .Values.sampleApp.name }}
